In [1]:
import numpy as np

In [2]:
test_input = """
939
7,13,x,x,59,x,31,19
"""

In [3]:
def parse_input(txt):
    rows = txt.strip().splitlines()
    timestamp = int(rows[0])
    busses = np.array([int(x) for x in rows[1].split(',') if x != 'x'])
    return timestamp, busses

In [4]:
timestamp, busses = parse_input(test_input)

In [5]:
busses

array([ 7, 13, 59, 31, 19])

In [6]:
x = timestamp / busses
next_bus = np.ceil(x) * busses - timestamp
idx = np.argmin(np.ceil(x) - x)
x, idx

(array([134.14285714,  72.23076923,  15.91525424,  30.29032258,
         49.42105263]), 2)

In [7]:
busses[idx]

59

In [8]:
min(next_bus)

5.0

In [9]:
with open('input.txt', 'r') as f:
    input_ = f.read()
    

In [10]:
timestamp, busses = parse_input(input_)

In [11]:
x = timestamp / busses
next_bus = np.ceil(x) * busses - timestamp
idx = np.argmin(np.ceil(x) - x)
x, idx

(array([52716.42105263, 24429.56097561, 27070.59459459,  1219.99025579,
        77047.07692308, 58918.35294118, 34538.34482759,  2163.30885529,
        43548.34782609]), 3)

In [12]:
busses[idx], min(next_bus), busses[idx] * min(next_bus)

(821, 8.0, 6568.0)

# Part 2

In [13]:
test_busses = [
    ('7,13,x,x,59,x,31,19', 1068781),
    ('17,x,13,19', 3417),
    ('67,7,59,61', 754018),
    ('67,x,7,59,61', 779210),
    ('67,7,x,59,61', 1261476),
    ('1789,37,47,1889', 1202161486),
]

In [14]:
def parse_busses(busses_txt):
    ids = busses_txt.split(',')
    delta_t = np.array([idx for idx, x in enumerate(ids) if x != 'x'])
    ids = np.array([int(x) for x in ids if x != 'x'])
    return ids, delta_t

In [212]:
def find_last_t(ids, delta_t, start_t=None, mult=None):
    delta_t_target = ids - (delta_t % ids)
    delta_t_target[0] = 0

    if start_t is None:
        t = ids[0]
    else:
        t = start_t
    if mult is None:
        mult = ids[0]
    step = 1000000 * mult
    while True:
        if t % ids[-1] == delta_t_target[-1]:
            return t
        t += mult


In [213]:
def progressive_find_t(ids, delta_t):
    start_t, mult = ids[0] - delta_t[0], ids[0]
    for idx in range(1, len(ids) + 1):
        t = find_last_t(ids[:idx], delta_t[:idx], start_t=start_t, mult=mult)
        print(idx, t)
        start_t, mult = t, np.prod(ids[:idx])
    return t

In [214]:
for b, exp in test_busses:
    ids, delta_t = parse_busses(b)
    res = progressive_find_t(ids, delta_t)
    print(exp, res)


1 7
2 77
3 350
4 70147
5 1068781
1068781 1068781
1 17
2 102
3 3417
3417 3417
1 67
2 335
3 6901
4 754018
754018 754018
1 67
2 201
3 4422
4 779210
779210 779210
1 67
2 335
3 16281
4 1261476
1261476 1261476
1 1789
2 30413
3 1288080
4 1202161486
1202161486 1202161486


In [215]:
with open('input.txt', 'r') as f:
    input_ = f.readlines()
    

In [216]:
input_

['1001612\n',
 '19,x,x,x,x,x,x,x,x,41,x,x,x,37,x,x,x,x,x,821,x,x,x,x,x,x,x,x,x,x,x,x,13,x,x,x,17,x,x,x,x,x,x,x,x,x,x,x,29,x,463,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,23\n']

In [217]:
ids, delta_t = parse_busses(input_[1])
ids, delta_t

(array([ 19,  41,  37, 821,  13,  17,  29, 463,  23]),
 array([ 0,  9, 13, 19, 32, 36, 48, 50, 73]))

In [218]:
progressive_find_t(ids, delta_t)

1 19
2 114
3 22705
4 109174
5 118427589
6 2271822742
7 91176279773
8 63333623272472
9 554865447501099


/Users/berkes/miniconda3/envs/scratch/lib/python3.5/site-packages/ipykernel/__main__.py:11: RuntimeWarning: overflow encountered in long_scalars


554865447501099